deploy-smart-contracts:
	forge build && forge install && ./deployment.sh

send-tokens:
	cd script && sh ./sendTokensOnMockMagiclaneApp.sh && cd ../

get-messages:
	cd script && sh ./getAllMessagesOnMockMagiclaneApp.sh && cd ../

